/// Defines the role of the message sender in a conversation.
enum MessageRole {
  /// A message sent by the end user.
  user,

  /// A message generated by the AI assistant.
  assistant,

  /// A system-level message used to instruct the AI on behavior.
  system,
}

/// Represents a single message within an AI-powered conversation.
///
/// Each [ChatMessage] contains the text [content], the [role] of the sender,
/// and an optional set of [metadata] for structured data like itineraries or
/// flight information.
class ChatMessage {
  /// Creates a [ChatMessage] from a JSON map.
  ///
  /// This is essential for loading chat history from local storage or
  /// parsing API responses.
  factory ChatMessage.fromJson(Map<String, dynamic> json) {
    return ChatMessage(
      content: json['content'] as String,
      role: _parseRole(json['role'] as String),
      timestamp: json['timestamp'] != null
          ? DateTime.parse(json['timestamp'] as String)
          : null,
      metadata: json['metadata'] as Map<String, dynamic>?,
    );
  }

  /// Creates a new [ChatMessage] instance.
  ///
  /// If [timestamp] is not provided, it defaults to [DateTime.now].
  ChatMessage({
    required this.content,
    required this.role,
    DateTime? timestamp,
    this.metadata,
  }) : timestamp = timestamp ?? DateTime.now();

  /// The text content of the message.
  final String content;

  /// The role of the entity that sent this message.
  final MessageRole role;

  /// The date and time when the message was created.
  final DateTime timestamp;

  /// Optional structured data associated with this message.
  ///
  /// This can be used to store specialized AI outputs, such as JSON-formatted
  /// flight bookings, hotel details, or tool-call results.
  final Map<String, dynamic>? metadata;

  /// Converts the message into a JSON-compatible map.
  ///
  /// Useful for sending data to the LLM or saving history to disk.
  Map<String, dynamic> toJson() {
    return {
      'role': role.name,
      'content': content,
      'timestamp': timestamp.toIso8601String(),
      if (metadata != null) 'metadata': metadata,
    };
  }

  /// Helper to safely parse roles from strings.
  static MessageRole _parseRole(String roleStr) {
    switch (roleStr.toLowerCase()) {
      case 'user':
        return MessageRole.user;
      case 'system':
        return MessageRole.system;
      case 'assistant':
      default:
        return MessageRole.assistant;
    }
  }

  /// Returns true if this message contains additional [metadata].
  bool get hasMetadata => metadata != null && metadata!.isNotEmpty;
}
